package:
  name: saltswap-dev
  version: 0.5

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - openmm >= 7.1
    - openmmtools >= 0.9.4
    - netcdf4
    - pytest

  run:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - openmm >= 7.1
    - openmmtools >= 0.9.4
    - netcdf4

test:
  requires:
    - pytest
  imports:
    - saltswap

about:
  home: https://github.com/choderalab/saltswap
  license: MIT License
